package com.stockcontrolathome.authentication.repository.AuditoryConfirmRegistrationToken.custom;

import com.stockcontrolathome.authentication.entity.AuditoryConfirmRegistrationToken;

public interface AuditoryConfirmRegistrationTokenRepositoryCustom {

    void saveAuditoryConfirmRegistrationToken(AuditoryConfirmRegistrationToken auditoryConfirmRegistrationToken);
}
