version: '3'

services:
  ##postgres database for Inventory
  db-authentication:
    container_name: db-authentication
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_authentication
      POSTGRES_USER: stockcontrolathome
      POSTGRES_PASSWORD: stockcontrolathome
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

