package com.stockcontrolathome.authentication.auditory.confirmregistrationtoken.service.impl;

import com.stockcontrolathome.authentication.auditory.confirmregistrationtoken.dto.auditoryconfirmregistrationtoken.request.AuditoryConfirmRegistrationTokenRequest;
import com.stockcontrolathome.authentication.auditory.confirmregistrationtoken.entity.AuditoryConfirmRegistrationToken;
import com.stockcontrolathome.authentication.auditory.confirmregistrationtoken.enums.EAuditoryConfirmRegistrationTokenState;
import com.stockcontrolathome.authentication.auditory.confirmregistrationtoken.mapper.AuditoryConfirmRegistrationTokenMapper;
import com.stockcontrolathome.authentication.auditory.confirmregistrationtoken.repository.custom.AuditoryConfirmRegistrationTokenRepositoryCustom;
import com.stockcontrolathome.authentication.auditory.confirmregistrationtoken.service.AuditoryConfirmRegistrationTokenService;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
@AllArgsConstructor
public class AuditoryConfirmRegistrationTokenServiceImpl implements AuditoryConfirmRegistrationTokenService {

    private final AuditoryConfirmRegistrationTokenRepositoryCustom auditoryConfirmRegistrationTokenRepositoryCustom;

    private final AuditoryConfirmRegistrationTokenMapper auditoryConfirmRegistrationTokenMapper;

    @Override
    public void saveAuditoryConfirmRegistrationToken(AuditoryConfirmRegistrationTokenRequest auditoryConfirmRegistrationTokenRequest, EAuditoryConfirmRegistrationTokenState newState) {
        AuditoryConfirmRegistrationToken auditoryConfirmRegistrationToken = this.auditoryConfirmRegistrationTokenMapper.auditoryConfirmRegistrationTokenRequestToAuditoryConfirmRegistrationTokenEntity(auditoryConfirmRegistrationTokenRequest);
        auditoryConfirmRegistrationToken.setSentencedDate(LocalDateTime.now());
        auditoryConfirmRegistrationToken.setState(newState);
        this.auditoryConfirmRegistrationTokenRepositoryCustom.saveAuditoryConfirmRegistrationToken(auditoryConfirmRegistrationToken);
    }
}
