package com.stockcontrolathome.authentication.auditory.confirmregistrationtoken.repository.custom;

import com.stockcontrolathome.authentication.auditory.confirmregistrationtoken.entity.AuditoryConfirmRegistrationToken;

public interface AuditoryConfirmRegistrationTokenRepositoryCustom {

    void saveAuditoryConfirmRegistrationToken(AuditoryConfirmRegistrationToken auditoryConfirmRegistrationToken);
}
